### PR TITLE
Fix IoU definition

### PR DESCRIPTION
**Pull request by yanfengliu**
This PR fixes the definition of IoU discussed in this [issue](https://github.com/broadinstitute/keras-rcnn/issues/47).

### CODE REVIEW

**Comment by yanfengliu** [comment]
It gave the following error, but I did not touch that part. 
`ImportError: No module named block.temporal`

**Comment by hgaiser** [comment]
For the error, see https://github.com/broadinstitute/keras-rcnn/pull/46

**Comment by yhenon** [comment]
This calls `intersection()` twice with the same arguments, which isn't that desirable. IMO a better way is:
```
def union(au, bu, area_intersection):
	area_a = (au[2] - au[0]) * (au[3] - au[1])
	area_b = (bu[2] - bu[0]) * (bu[3] - bu[1])
	area_union = area_a + area_b - area_intersection
	return area_union


def intersection(ai, bi):
	x = max(ai[0], bi[0])
	y = max(ai[1], bi[1])
	w = min(ai[2], bi[2]) - x
	h = min(ai[3], bi[3]) - y
	return max(0, w*h)


def iou(a, b):
	# a and b should be (x1,y1,x2,y2)

	if a[0] >= a[2] or a[1] >= a[3] or b[0] >= b[2] or b[1] >= b[3]:
		return 0.0

	area_i = intersection(a, b)
	area_u = union(a, b, area_i)

	return float(area_i) / float(area_u)
```

**Comment by yanfengliu** [comment]
@hgaiser Thanks! I merged your pull request into mine just now

**Comment by yanfengliu** [comment]
@yhenon Thank you for the suggestion! I will change the code a little bit.

**Comment by hgaiser** [comment]
Actually I think it'd be better if this PR only contains the fixes for IOU,
not also the fixes for keras-resnet.

**Comment by yanfengliu** [comment]
@hgaiser Sounds good. I will revert the commit.

**Comment by hgaiser** [comment]
Nice :) if you can squash the commits to one clean commit, you got my thumbs up.

**Comment by yanfengliu** [comment]
@hgaiser I tried to squash the commits but they have been pushed, so I don't know if there is some other way to change how it looks online. Sorry for the messy commits. I can close this one and open a new one if necessary.

**Pull request closed without merging**
